title: "Oscar Gaitan"
description: 
baseurl: "/academic-profile"
url: "https://ogait001.github.io"
theme: minima

header_pages: []

google_site_verification: PJlDuChhSovdT4_1ylBNm5jt4_zXlfe53rhJkHQSi7o

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
