title: "Oscar Gaitan"
description: "Essays on philosophy of time, ontology, phenomenology, theology, and eschatology"
baseurl: "/academic-profile"
url: "https://ogait001.github.io"
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
